#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#liste_equipement:
#  path: /api/equipements
#  controller: App\Controller\EquipementsController::index

#modifier_equipement:
#  path: /api/ajouter
#  controller: App\Controller\EquipementsController::ajout_equipement